
run:
	#sed -i '/^create_project/s/.*/create_project $$\{_xil_proj_name_\} . -part xcvu13p-fhgb2104-2-i /' project.tcl
	#rm create_project.tcl
	#git co create_project.tcl
	#sed -i '/^create_project/s/$$/ -force/' create_project.tcl
	vivado -mode batch -source build.tcl
